<a href="https://colab.research.google.com/github/yelim421/SolarPower/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd /content/drive/MyDrive/Solar_Power

/content/drive/MyDrive/Solar_Power

In [5]:
import itertools
import tensorflow as tf
from keras.models import load_model
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler

In [6]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
with open('done_preprocessing.csv', 'r') as f:
    data = pd.read_csv(f)

In [7]:
data.head()

,aerosol,year,month,day,hour,Temp(C),Prec(mm),Humidity(%),Dew_Point(C),Solar_Radiation(MJ/m2),Snowfall(cm),3hr_New_Snowfall(cm),Cloud_Cover(1/10),Middle_Low_Cloud_Cover(1/10),Lowest_Cloud_Height(100m),Visibility(10m),30cm_Ground_Temperature(C),power,d2m,t2m,time,Temp_Dew_Point_Diff,log_aerosol,log_Prec(mm),log_Snowfall(cm),t2m_d2m_diff,power_lag_1,power_lag_2,power_lag_3,power_rolling_mean_24,power_rolling_std_24,day_of_week,is_weekend,Temp_Humidity_Interaction,Visibility_Cloud_Interaction
0,22.0,2013,3,20,17,3.9,0.0,72.0,-0.6,1.40,0.0,0.0,0.000000,0.000000,10.0,2500.000000,10.4,5356800.0,267.97684,273.97412,2013-03-20 17:00:00,4.5,3.135494,0.0,0.0,5.99728,4492800.0,4684800.0,4742400.0,3204400.0,2.686564e+06,2,0,-2.34,0.000000
1,33.0,2013,3,20,18,2.1,0.0,69.0,-3.0,0.66,0.0,0.0,1.000000,1.000000,10.0,2500.000000,10.4,2726400.0,267.81885,273.76404,2013-03-20 18:00:00,5.1,3.526361,0.0,0.0,5.94519,5356800.0,4492800.0,4684800.0,3317600.0,2.602003e+06,2,0,-6.30,2500.000000
2,40.0,2013,3,20,19,0.7,0.0,68.0,-4.5,0.07,0.0,0.0,0.923077,0.923077,10.0,2461.538462,10.3,201600.0,267.64540,273.56427,2013-03-20 19:00:00,5.2,3.713572,0.0,0.0,5.91887,2726400.0,5356800.0,4492800.0,3292000.0,2.630551e+06,2,0,-3.15,2272.189349
3,48.0,2013,3,21,7,-2.3,0.0,72.0,-6.6,0.01,0.0,0.0,0.000000,0.000000,10.0,2000.000000,8.3,28800.0,268.66763,279.48187,2013-03-21 07:00:00,4.3,3.891820,0.0,0.0,10.81424,201600.0,2726400.0,5356800.0,3172400.0,2.713142e+06,3,0,15.18,0.000000
4,38.0,2013,3,21,8,-0.6,0.0,60.0,-7.4,0.40,0.0,0.0,0.000000,0.000000,10.0,2000.000000,8.1,1468800.0,269.65826,279.11100,2013-03-21 08:00:00,6.8,3.663562,0.0,0.0,9.45274,28800.0,201600.0,2726400.0,3005600.0,2.688563e+06,3,0,4.44,0.000000

In [8]:
data = pd.concat([data.drop('power', axis=1), data['power']], axis=1)

data.head()

,aerosol,year,month,day,hour,Temp(C),Prec(mm),Humidity(%),Dew_Point(C),Solar_Radiation(MJ/m2),Snowfall(cm),3hr_New_Snowfall(cm),Cloud_Cover(1/10),Middle_Low_Cloud_Cover(1/10),Lowest_Cloud_Height(100m),Visibility(10m),30cm_Ground_Temperature(C),d2m,t2m,time,Temp_Dew_Point_Diff,log_aerosol,log_Prec(mm),log_Snowfall(cm),t2m_d2m_diff,power_lag_1,power_lag_2,power_lag_3,power_rolling_mean_24,power_rolling_std_24,day_of_week,is_weekend,Temp_Humidity_Interaction,Visibility_Cloud_Interaction,power
0,22.0,2013,3,20,17,3.9,0.0,72.0,-0.6,1.40,0.0,0.0,0.000000,0.000000,10.0,2500.000000,10.4,267.97684,273.97412,2013-03-20 17:00:00,4.5,3.135494,0.0,0.0,5.99728,4492800.0,4684800.0,4742400.0,3204400.0,2.686564e+06,2,0,-2.34,0.000000,5356800.0
1,33.0,2013,3,20,18,2.1,0.0,69.0,-3.0,0.66,0.0,0.0,1.000000,1.000000,10.0,2500.000000,10.4,267.81885,273.76404,2013-03-20 18:00:00,5.1,3.526361,0.0,0.0,5.94519,5356800.0,4492800.0,4684800.0,3317600.0,2.602003e+06,2,0,-6.30,2500.000000,2726400.0
2,40.0,2013,3,20,19,0.7,0.0,68.0,-4.5,0.07,0.0,0.0,0.923077,0.923077,10.0,2461.538462,10.3,267.64540,273.56427,2013-03-20 19:00:00,5.2,3.713572,0.0,0.0,5.91887,2726400.0,5356800.0,4492800.0,3292000.0,2.630551e+06,2,0,-3.15,2272.189349,201600.0
3,48.0,2013,3,21,7,-2.3,0.0,72.0,-6.6,0.01,0.0,0.0,0.000000,0.000000,10.0,2000.000000,8.3,268.66763,279.48187,2013-03-21 07:00:00,4.3,3.891820,0.0,0.0,10.81424,201600.0,2726400.0,5356800.0,3172400.0,2.713142e+06,3,0,15.18,0.000000,28800.0
4,38.0,2013,3,21,8,-0.6,0.0,60.0,-7.4,0.40,0.0,0.0,0.000000,0.000000,10.0,2000.000000,8.1,269.65826,279.11100,2013-03-21 08:00:00,6.8,3.663562,0.0,0.0,9.45274,28800.0,201600.0,2726400.0,3005600.0,2.688563e+06,3,0,4.44,0.000000,1468800.0

In [9]:
data.to_csv('done_preprocessing.csv', index=False)

In [10]:

# Selecting features and target
X = data.drop(columns=['power', 'time'])
y = data['power']

# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
date_cols = ['year', 'month', 'day', 'hour', 'day_of_week', 'is_weekend']

In [17]:
def compare_cols(cols):
    s=1
    for i in cols:
        print(f"feature is: {i}")
        train_unique_count = len(X_train[i].unique())
        test_unique_count = len(X_test[i].unique())
        print(f"# of train unique values is: {train_unique_count}")
        print(f"# of test unique values is: {test_unique_count}")
        all_values = set(X_train[i]).union(set(X_test[i]))
        D = pd.DataFrame({'Unique': list(all_values)})
        D['train_count'] = [len(X_train[X_train[i] == j]) for j in all_values]
        D['train_percent'] = (D['train_count']/ len(X_train)) * 100
        D['test_count'] = [len(X_test[X_test[i] == j]) for j in all_values]
        D['test_percent'] = (D['test_count']/ len(X_test)) * 100
        print(D.sort_values('train_count', ascending = False))
        print('--------------------')
        print(f"Total number of navigated features is: {s}")
        s+=1
        print('--------------------')

In [18]:
compare_cols(cols = date_cols)

feature is: year
# of train unique values is: 10
# of test unique values is: 10
   Unique  train_count  train_percent  test_count  test_percent
4    2017         3597      10.294791         881     10.085861
6    2019         3592      10.280481         865      9.902690
9    2022         3581      10.248998         889     10.177447
3    2016         3580      10.246136         878     10.051517
7    2020         3574      10.228964         896     10.257584
2    2015         3561      10.191757         861      9.856898
8    2021         3552      10.165999         912     10.440756
5    2018         3523      10.082999         890     10.188895
1    2014         3521      10.077275         917     10.497997
0    2013         2859       8.182599         746      8.540355
--------------------
Total number of navigated features is: 1
--------------------
feature is: month
# of train unique values is: 12
# of test unique values is: 12
    Unique  train_count  train_percent  test_count  test_percent
4        5         3483       9.968517         903     10.337722
5        6         3477       9.951345         834      9.547796
6        7         3413       9.768174         858      9.822553
7        8         3255       9.315970         850      9.730967
3        4         3082       8.820836         788      9.021179
8        9         3041       8.703492         727      8.322839
2        3         2839       8.125358         681      7.796222
9       10         2795       7.999428         706      8.082427
10      11         2537       7.261019         671      7.681740
11      12         2506       7.172295         605      6.926159
1        2         2264       6.479679         556      6.365197
0        1         2248       6.433887         556      6.365197
--------------------
Total number of navigated features is: 2
--------------------
feature is: day
# of train unique values is: 31
# of test unique values is: 31
    Unique  train_count  train_percent  test_count  test_percent
9       10         1173       3.357184         266      3.045220
22      23         1171       3.351460         273      3.125358
15      16         1166       3.337149         261      2.987979
20      21         1164       3.331425         294      3.365770
21      22         1163       3.328563         291      3.331425
1        2         1159       3.317115         282      3.228392
26      27         1158       3.314253         284      3.251288
6        7         1157       3.311391         271      3.102461
27      28         1155       3.305667         289      3.308529
0        1         1155       3.305667         288      3.297081
23      24         1151       3.294219         290      3.319977
7        8         1150       3.291357         284      3.251288
18      19         1148       3.285633         276      3.159702
24      25         1148       3.285633         293      3.354322
25      26         1146       3.279908         289      3.308529
16      17         1145       3.277046         275      3.148254
19      20         1144       3.274184         288      3.297081
2        3         1144       3.274184         272      3.113910
13      14         1143       3.271322         286      3.274184
4        5         1141       3.265598         282      3.228392
8        9         1140       3.262736         292      3.342873
3        4         1138       3.257012         304      3.480252
12      13         1136       3.251288         290      3.319977
14      15         1129       3.231254         310      3.548941
11      12         1127       3.225529         293      3.354322
17      18         1126       3.222667         295      3.377218
10      11         1109       3.174013         306      3.503148
5        6         1109       3.174013         308      3.526045
28      29         1083       3.099599         280      3.205495
29      30         1062       3.039496         283      3.239840
30      31          700       2.003434         140      1.602748
--------------------
Total number of navigated features is: 3
--------------------
feature is: hour
# of train unique values is: 15
# of test unique values is: 15
    Unique  train_count  train_percent  test_count  test_percent
9       15         2868       8.208357         701      8.025186
10      16         2862       8.191185         706      8.082427
8       14         2858       8.179737         711      8.139668
7       13         2857       8.176875         710      8.128220
5       11         2854       8.168288         706      8.082427
6       12         2846       8.145392         717      8.208357
4       10         2842       8.133944         714      8.174013
11      17         2801       8.016600         752      8.609044
3        9         2798       8.008014         721      8.254150
12      18         2709       7.753291         666      7.624499
2        8         2464       7.052089         618      7.074986
13      19         1663       4.759588         460      5.266171
1        7         1466       4.195764         329      3.766457
14      20          778       2.226674         154      1.763022
0        6          274       0.784201          70      0.801374
--------------------
Total number of navigated features is: 4
--------------------
feature is: day_of_week
# of train unique values is: 7
# of test unique values is: 7
   Unique  train_count  train_percent  test_count  test_percent
2       2         5016      14.356039        1237     14.161420
1       1         5003      14.318832        1240     14.195764
3       3         4999      14.307384        1258     14.401832
0       0         4995      14.295936        1202     13.760733
5       5         4977      14.244419        1279     14.642244
6       6         4977      14.244419        1247     14.275902
4       4         4973      14.232971        1272     14.562106
--------------------
Total number of navigated features is: 5
--------------------
feature is: is_weekend
# of train unique values is: 2
# of test unique values is: 2
   Unique  train_count  train_percent  test_count  test_percent
0       0        24986      71.511162        6209     71.081855
1       1         9954      28.488838        2526     28.918145
--------------------
Total number of navigated features is: 6
--------------------

In [4]:

# Applying MinMaxScaler
X_scaler = MinMaxScaler()
y_scaler = MinMaxScaler()

# Scaling the features
X_train_scaled = X_scaler.fit_transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Scaling the target variable
y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1, 1)).flatten()
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1, 1)).flatten()

print(X_train_scaled.shape, y_train_scaled.shape, X_test_scaled.shape, y_test_scaled.shape)